name: summa
channels:
  - conda-forge
dependencies:
  - conda:
    - xarray>=0.11.0
    - pandas
    - netcdf4>=1.2.5
    - numpy>=1.11.2
    - dask
    - distributed
    - toolz
    - pytest
    - fiona
    - cartopy
    - shapely
    - seaborn
    - matplotlib
    - geopandas
    - jupyter
  - pip
  - pip:
    - hs_restclient
